### PR TITLE
Remove some Gui ASM

### PR DESCRIPTION
**Pull request by mezz**
There's still a lot of Gui ASM, this PR replaces and removes some of it.
Really takes a while to go through this stuff, I thought I'd be able to get rid of more in the time I had!

### CODE REVIEW

**Comment by covers1624** [comment]
Nice, Though the generic event handlers would be more suited in a generic EventHandler class, The ContainerEventHandler is meant to be specifically for JEI integration. Ill check if NEI has a generic EventHandler class, if not something like nei/handler/EventHandler would be better.

**Comment by covers1624** [comment]
ClientHandler seems to be the place.

**Comment by mezz** [comment]
Ok I'll move those then.

**Comment by mezz** [comment]
Updated and checked it still works

**Pull request merged**
